CREATE TABLE etapa (
	id BIGINT(20) NOT NULL AUTO_INCREMENT,
	nome VARCHAR(255) NOT NULL,
	posicao INT,
	PRIMARY KEY(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE cartao 
ADD etapa_id BIGINT(20);

ALTER TABLE cartao
ADD CONSTRAINT FOREIGN KEY (etapa_id) REFERENCES etapa(id);